services:
  db:
    image: mysql
    ports:
      -  "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: wordpressdb

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"  # Change port as needed
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass123
